### ISSUE TITLE
I need to be able to remove or significantly lower the delay at which the "change" event is fired.

### ISSUE THREAD

**Issue by m-andrew-albright** [froala/aurelia-froala-editor#20]
I'm binding via `two-way`, but it's only updating the property after I stop typing for about a half a second.  I need to remove this delay and I can't find in the documentation for froala how to do that.

**Comment by stefanneculai** [comment]
The editor is triggering contentChanged while you type based on the `typingTimer`. The minimum value it can be set to is 500 because if you go lower than that then you would esperience some lag between keystrokes if the html is large enough. For example, you could listen on keyup instead of contentChanged and get the edited html there, but we do not recommend that.

**Comment by smajl** [comment]
@stefanneculai Hi. Currently in latest version, the binded value seems to be only updated on blur event. Undo action is also problematic, because now you have to do focus-blur cycle to propagate the change. Did anything changed in configuration? How to reintroduce timed updates back?

**Comment by stefanneculai** [comment]
It is changing on `contentChanged` as well: https://github.com/froala/aurelia-froala-editor/blob/master/src/froala-editor.js#L59.
